### PR TITLE
 Update metadata | Add .gitignore & COPYING

### PR DESCRIPTION
**Pull request by vipulgupta2048**
**Updated following parameters**
`url`, `license`, `tags`, summary

Added .gitignore file and COPYING

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@quozl Any changes ?

**Comment by quozl** [comment]
Thanks.  Reviewed to 107ef9e.  Please consider;

* [ ] the COPYING file does not properly express the wishes of the original author; while we have no legal obligation to do so, and while the Public Domain would let us change copyright owner and assert GPLv3+ over the entire work, I'm not sure that is needed; so please add a COPYING that expresses the wishes of the original author that their code is Public Domain, and rename your proposed COPYING file to COPYING.GPLv3,
* [ ] the tag _Utilities_ seems vague; utility software is general purpose for using the resources of a system, but this activity is about learning to read and perceive time.

**Comment by vipulgupta2048** [comment]
@quozl Changes made as requested. Do check the Public Domain CC0 license, if its right or not.

**Comment by quozl** [comment]
Thanks.  Reviewed to ef2161a.

* [ ] your COPYING file does not properly express the wishes of the original author; they said _Public Domain_, but you've added a COPYING file with a CC0 license, which says far more.
* [ ] the tag _Science_ is vague; maybe you should use _Time_?  You seem to be suffering from a badly written list of tags; you might seek a wider community contribution to the tag list.  Where is the list?

**Comment by vipulgupta2048** [comment]
- I couldn't find the text, for Public Domain quite frankly. To be honest, if we have no license over the codebase wouldn't it automatically mean public domain. 
- Well, the list is in [`bundle/_init_.py`](https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/src/sugar3/bundle/__init__.py), I am though suffering :sweat: with limited tags yes, I am already doing something on the side to remedy that, all new tags that we are adding are already being added to the list in local. When we are done with most of the PR's, I will make another PR to the `sugar-toolkit-gtk3` repo to add those tags and also get some community contribution.

**Comment by quozl** [comment]
In this software, Public Domain is not a license, but a complete forfeit of rights.  There is no text for Public Domain other than "Public Domain".  See https://en.wikipedia.org/wiki/Public_domain

We could take the Public Domain source code and assert a new copyright on it, but I don't think we need to; it is enough to leave it as it is.

**Comment by vipulgupta2048** [comment]
Cool. Pushing the same.

**Pull request merged**
