### PR TITLE
translate.sugarlabs.org synchronisation

### PR DESCRIPTION
**Pull request by quozl**
@leonardcj, does this look right?  The "What Time Is It?" sections look odd to me.

### CODE REVIEW

**Comment by leonardcj** [comment]
It is not odd, the "What Time Is It?" is simply a bloody mess.  A genuine "how NOT to do i18n" example.  It tries to do something  very clever by making the talking clock sound like it is reading an analog round clock face instead of reading out digits.  Instead of "twelve forty five", it should say "a quarter to one".  Unfortunately to accomplish this clever trick, localizers are given completely inadequate guidance and it is only done correctly in a handful of languages because it requires creating a very specialized bit of mark-up language that nearly no localizer comprehends.  It is correctly localized in English, Spanish, probably French and maybe a few other languages, but usually the string is translated literally as 'What time is it?" and the best I can do is mark it as fuzzy (needs work) in Pootle until I can walk a skilled localizer through the intracacies of creating the correct mark-up.

**Comment by quozl** [comment]
Heh.  Thanks.  Is there a better way to do it in the source?

**Comment by leonardcj** [comment]
This can't be the only open source talking clock app in the world, but I have not looked for examples of how to do this in a L10n-friendly manner.

**Comment by leonardcj** [comment]
You will probably see that in some instances I have seeded that string with the English markup example, or if appropriate (e.g. Latin American indigenous languages) with the Spanish example.  I will typically mark the string as fuzzy (needs work) in Pootle when seeding it in that way.  I think I might get better results by creating a wiki page walking localizers through the "pretend to be analog" concept with heavily annotated examples of the markup's structure.  Honestly that string is the bane of my existence. . .

**Comment by leonardcj** [comment]
In any event, I think the POT needs to have some of the translator's comments (or something better) that exists in the current template on Pootle.

**Comment by quozl** [comment]
Looked briefly at the code.  The way it works places a high load on translators.  Yet the feature provided is mostly of historical or cultural value, and as you say is only translated properly in a few languages.  Another option is to remove the feature, and switch to literally speaking the hour and minute; e.g. "twelve, forty five."

**Comment by leonardcj** [comment]
Speaking only for myself (and maybe for some localizers), I would have no objection to such a change to a speaking digital clock as opposed to a speaking analog clock.  The embedding of many common strings with the Speak Activity (but with some differences in the voices listed) is another source of i18n dis-satisfaction on my part.  A real rework the code might synch up the e-speak versions as well.

**Comment by EmilyOng** [comment]
> I think I might get better results by creating a wiki page walking localizers through the "pretend to be analog" concept with heavily annotated examples of the markup's structure. Honestly that string is the bane of my existence. . .

I could help with this in addition to the changes made in #15 @leonardcj

**Comment by leonardcj** [comment]
@EmilyOng  that would be a wonderful gift to localizers (and users)

**Comment by EmilyOng** [comment]
Sure!

As per IRC discussion with @walterbender:

I suspect you want something like: "_(%s) _(%s)-_(%s)" % (h, m10, m1)
10:14 PM where m10 are the tens and m1 are the units
10:15 PM e.g., forty and five
10:15 PM so a much less complex rule
10:15 PM maybe this breaks down for R2L languages?
10:16 PM You could ask cjl

What do you think of this?

**Comment by EmilyOng** [comment]
https://github.com/EmilyOng/clock-activity/wiki

**Comment by quozl** [comment]
Thanks for the Wiki changes, but please also make sure the changes are added to README.  I'll also make a new issue for converting the README to markdown.

**Pull request merged**
